language: python
# Other versions are installed by default. Configure tox.ini to use them.
python:
    - "2.7"
    - "3.2"

# Sets Travis' venv to check for system site packages
# This makes numpy imports work
# See: http://stackoverflow.com/questions/17224389/scipy-importerror-on-travis-ci
virtualenv:
    system_site_packages: true

# Configure the build system
before_install:
    # This fixes an issue with Travis already having some ZMQ stuff installed
    # See: https://github.com/travis-ci/travis-ci/issues/1715
    - sudo rm /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
    # Install system-level requirements. Ideally, we'd do this with pip. Not possible.
    - sudo apt-get update -qq
    - sudo apt-get install -y python-smbus libzmq-dev python-zmq python-yaml python-numpy

# Ideally, we'd install everything via pip. Not always possible.
#install: pip install -r requirements.txt

# Command to run tests
script: tox -vv

# Sets Travis to run these test jobs in parallel, report them independently
env:
    - TOXENV=py27
    - TOXENV=docs
    - TOXENV=pep8

# Configure notifications
notifications:
    email:
        recipients:
            - dfarrell07@gmail.com
    on_success: always
    on_failure: always
