language: python
python:
    - "3.2"
    - "2.7"
    - "pypy"
# Install dependencies
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y python-smbus python-zmq python-yaml python-numpy
install: pip install -r requirements.txt
# Run tests
script: tox
# Configure notifications
notifications:
    email:
        recipients:
            - dfarrell07@gmail.com
        on_success: change
        on_failure: change
