IR_PID : {
        "North": {
            "diff":[1.1, 0.04, 0.0],
            "dist":[0, 0, 0]
            },
        "East":  {
            "diff":[1.1, 0.04, 0.0],
            "dist":[0, 0, 0]
            },
        "South": {
            "diff":[1.1, 0.04, 0.0],
            "dist":[0, 0, 0]
             },
        "West":  {
            "diff":[1.1, 0.04, 0.0],
            "dist":[0, 0, 0]
            }

}

IR_Bias : {
        "North Left": 0, "North Right": 0, "East Top": -40, "East Bottom": 0, "South Right": 0, "South Left": 0, "West Bottom": 0, "West Top": 0
                                                                                                                                                      }

