#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.msp430.elf.MSP430{1,0,4.1,5
#
main.xe430: package/cfg/main.xe430.mak

clean::
	-$(RM) package/cfg/main.xe430.mak
