#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          bbb
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Beaglebone Black
# Description:       Beaglebone Black hardware setup
### END INIT INFO

case "$1" in
start|reload|force-reload|restart)
        /root/startup/setup_all.sh
        ;;
stop)
        exit 0
        ;;
*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0

