# Used when running unit tests and ctrl server.
testing : false
# Used for testing individual pices of hardware.
test_mode: {
    color_sensor: true,
    ADC: true,
    DMCC: true,
    stepper: true,
    motor: true,
    servo: true,
}

dmcc_drive_motors: {

    front_left: { board_num: 1, motor_num: 1 },
    back_left: { board_num: 1, motor_num: 2 },
    front_right: { board_num: 0, motor_num: 1, invert: True},
    back_right: { board_num: 0, motor_num: 2, invert: True }

}

logging: {log_file: bot/logs/bot.log, file_handler_level: DEBUG, stream_handler_level: INFO}  # Logging options
test_pwm_base_dir: bot/simulator/pins/pwm/pwm
test_gpio_base_dir: bot/simulator/pins/gpio/gpio
test_adc_base_dir: bot/simulator/pins/adc
server_protocol: tcp
server_bind_host: "*"  # Special hostname servers bind to, for listening on all interfaces
server_host: 127.0.0.1  # Default hostname clients connect to
ctrl_server_port: 60000  # Port used to send control messages to the bot
pub_server_port: 60001  # PubServer publishes bot data on this port
color_sensor: {LED_PWM: 5, ready_signal: 72}
